name: app_hub_upgrader
description: "A Flutter package for checking app version updates from API and displaying customizable update dialogs."
version: 1.0.1+2
homepage: https://github.com/aifgrouplaos/app_hub_upgrader

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true